### ISSUE TITLE
python101

### ISSUE THREAD

**Issue by smu095** [smu095/presentations#1]
# TODO:
- [x] Organise into folders, something like `imgs`, `markdown` and `scripts`?
- [x] Fix all broken links in .md-files.
- [ ] Add **Resources** section to all .md-files.
- [x] Establish consistent heading formatting in all .md-files.
- [x] Rename `black.py`.
