### ISSUE TITLE
mcmc-pymc-101

### ISSUE THREAD

**Issue by smu095** [smu095/presentations#12]
# Todo-list

The following todo-list is meant to give an overview over the most important tasks going forward. Leave a comment if you want to be assigned to a particular task or if you feel others should be added, and I will update the issue accordingly.

**Date for presentation:** 17.02.2020

## Presentation
- [X] ~~Decide on format for slides. I suggest using LaTeX as it is easy to keep under source control.~~
- [x] Delegate responsibilities for parts 1 and 2 of presentation.
  - [x] Part 1a: Theory (Markov chains, Monte Carlo methods and Markov Chain Monte Carlo) [@smu095 @solveigm].
  - [x] Part 1b: A couple of extra slides on priors. With example (linear regression?) [@solveigm]
  - [x] Part 1b: "But how do I calculate the likelihood?" Probability density function. (**By Wednesday:** [@smu095 @solveigm])

  - [ ] Part 2: Practice (PyMC3 workshop). Explain API and usage as a part of the example [Undetermined].
- [ ] Add slide motivating use of Bayes in business

### Presentation order
- @smu095 : 1-5, 12-24, 27 --> + example 2 (Golf)
- @solveigm : 6-11, 25-26 + example 1 (AR(1))

## Practical examples
- [x] By Wednesday, agree on:
  - [x] Find a relevant use case where uncertainty/transparency is important? I.e. where black box methods are not suitable/preferable [@solveigm].
  - [x] Maybe try to find a neat example where we minimise an expected loss function? [@smu095]

## Setup
- [X] ~~Write brief setup description and add to `README.md`.~~
- [x] ~~Enable master branch protection.~~
- [X] ~~Install necessary packages and `pip freeze > requirements.txt` for reproducibility.~~
- [x] Add .pdf to `.gitignore` [@smu095]
